# Generated by Django 6.0.2 on 2026-02-03 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_rename_research_interest_supervisorprofile_research_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentproposal',
            old_name='manual_preference',
            new_name='manual_preferences',
        ),
    ]
