# Generated by Django 6.0.2 on 2026-04-19 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('research_interests', models.JSONField(default=list)),
                ('suggested_projects', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('primary_project_format', models.JSONField(default=list)),
                ('capacity', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_manual_preferences', models.IntegerField(default=3, help_text='Maximum number of manual preferences a student can submit')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='StudentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic_description', models.TextField()),
                ('student_research_interests', models.JSONField(default=list)),
                ('technical_Skills', models.JSONField(default=list)),
                ('primary_project_format', models.JSONField(default=list)),
                ('manual_preferences', models.JSONField(default=list)),
                ('has_submitted', models.BooleanField(default=False)),
                ('has_pre_agreement', models.BooleanField(default=False)),
                ('allocated_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_students', to='allocation.supervisorprofile')),
                ('pre_agreed_supervisor', models.ForeignKey(blank=True, help_text='The specific academic the student has a prior arrangement with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_agreements', to='allocation.supervisorprofile')),
            ],
        ),
    ]
