# Generated by Django 6.0.2 on 2026-03-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic_description', models.TextField()),
                ('student_research_interests', models.JSONField(default=list)),
                ('programming_languages', models.JSONField(default=list)),
                ('project_category', models.JSONField(default=list)),
                ('manual_preferences', models.JSONField(default=list)),
                ('has_submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('research_interests', models.JSONField(default=list)),
                ('suggested_projects', models.JSONField(default=list)),
                ('required_skills', models.JSONField(default=list)),
                ('suggested_project_categories', models.JSONField(default=list)),
                ('capacity', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_manual_preferences', models.IntegerField(default=3, help_text='Maximum number of manual preferences a student can submit')),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
