# Generated by Django 6.0.2 on 2026-02-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorprofile',
            old_name='research_interest',
            new_name='research_interests',
        ),
    ]
