# Generated by Django 6.0.2 on 2026-04-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentproposal',
            old_name='technical_Skills',
            new_name='technical_skills',
        ),
    ]
