# Generated by Django 6.0.2 on 2026-04-26 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorprofile',
            old_name='primary_project_category',
            new_name='project_category',
        ),
    ]
