# Generated by Django 6.0.2 on 2026-03-30 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproposal',
            name='allocated_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_students', to='allocation.supervisorprofile'),
        ),
    ]
