# Generated by Django 6.0.2 on 2026-03-31 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_studentproposal_allocated_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproposal',
            name='has_pre_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentproposal',
            name='pre_agreed_supervisor',
            field=models.ForeignKey(blank=True, help_text='The specific academic the student has a prior arrangement with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_agreements', to='allocation.supervisorprofile'),
        ),
        migrations.AlterField(
            model_name='studentproposal',
            name='allocated_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocated_students', to='allocation.supervisorprofile'),
        ),
    ]
