# Generated by Django 6.0.2 on 2026-03-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_studentproposal_has_pre_agreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisorprofile',
            old_name='suggested_project_categories',
            new_name='project_categories',
        ),
    ]
