# Generated by Django 6.0.2 on 2026-04-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0004_rename_suggested_project_categories_supervisorprofile_project_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentproposal',
            old_name='programming_languages',
            new_name='primary_project_format',
        ),
        migrations.RenameField(
            model_name='studentproposal',
            old_name='project_category',
            new_name='technical_Skills',
        ),
    ]
